-- AlterTable
ALTER TABLE "pages" ADD COLUMN IF NOT EXISTS "htmlContent" TEXT;
ALTER TABLE "pages" ADD COLUMN IF NOT EXISTS "tableOfContents" JSONB;
ALTER TABLE "pages" ADD COLUMN IF NOT EXISTS "faq" JSONB;
